# Basic Ubuntu machine setup.
#
# Usage:
#
# 1. $ ansible-playbook ansible/roles/ubuntu.yml -i aaa.bbb.ccc.ddd,
# 2. $ ssh aaa.bbb.ccc.ddd
# 3. Install dotfiles!
---
- hosts: all
  remote_user: root
  vars:
    user: "{{ lookup('env', 'USER') }}"
  vars_prompt:
    - name: "password"
      prompt: "password for the remote user to set (when user does not exist yet)"
      private: yes
      encrypt: "sha512_crypt" # need to have python-passlib installed in local machine before we can use it ('pip install passlib')
      confirm: yes
      salt_size: 7
  tasks:
    - name: update/upgrade apt
      apt: upgrade=dist update_cache=yes

    - name: add primary user
      user: name={{ user }} shell=/bin/bash groups=sudo append=yes password={{ password }}

    - name: upload primary user ssh public key
      authorized_key: user={{ user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: disable root ssh login, disallow password authentication (and other sshd_config tweaks)
      lineinfile: dest=/etc/ssh/sshd_config state={{ item.state }} line="{{ item.line }}" regexp="{{ item.regexp }}"
      with_items:
        - { state: present, line: "PermitRootLogin no", regexp: "^PermitRootLogin" }
        - { state: present, line: "PasswordAuthentication no", regexp: "^PasswordAuthentication" }
        - { state: present, line: "UseDNS no", regexp: "^UseDNS" }
        - { state: present, line: "AllowUsers {{ user }}" ,regexp: "^AllowUsers" }
      notify:
        - reload ssh

    - name: Enable SSH Agent forwarding for sudo
      lineinfile: dest=/etc/sudoers state=present insertafter='^Defaults' line='Defaults	env_keep+=SSH_AUTH_SOCK' validate='visudo -cf %s'

    - name: Install packages
      apt: "pkg={{ item }} state=present"
      with_items:
        - curl
        - fail2ban

  handlers:
    - name: reload ssh
      service: name=ssh state=restarted
